name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@702521529f0ebea89257b1297490379a0ec56976 # main

  renovate:
    name: Renovate Config
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@702521529f0ebea89257b1297490379a0ec56976 # main
