name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@b914995b0f823a9db107ec78a05c59d428fbb596 # main

  renovate:
    name: Renovate Config
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@b914995b0f823a9db107ec78a05c59d428fbb596 # main
