name: Lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    name: Super Linter
    uses: harryzcy/github-actions/.github/workflows/linter.yml@3ce6f550e4cc0f77ae4ce84604c55e9b41dab049 # main

  renovate:
    name: Renovate Config
    uses: harryzcy/github-actions/.github/workflows/renovate.yml@3ce6f550e4cc0f77ae4ce84604c55e9b41dab049 # main
